on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # For non-secret environment variables, there's no need to use GitHub's
      # repository secrets. These are just here for demonstration purposes.
      PUBLIC_ENV_VAR_ONE: ${{ secrets.ENV_VAR_ONE }}
      PUBLIC_ENV_VAR_TWO: ${{ secrets.ENV_VAR_TWO }}
      NODE_ENV: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Set up Playwright
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run test
  # build-and-deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4
  #     - name: Authenticate with Google Cloud Platform
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  #     - name: Install GCloud CLI
  #       uses: google-github-actions/setup-gcloud@v2
  #     - name: Build and deploy to Cloud Run
  #       run: gcloud run deploy app --source . --platform managed --memory 128Mi --region us-central1 --allow-unauthenticated --project ${{ secrets.GCP_PROJECT_ID }} --set-env-vars PUBLIC_ENV_VAR_ONE=${{ secrets.ENV_VAR_ONE }},PUBLIC_ENV_VAR_TWO=${{ secrets.ENV_VAR_TWO }}
# It is important that you not incude private secrets this way if you don't want
# others with project Viewer permissions or greater in the GCP project to be
# able to see them. Instead, use Secret Manager as described in the page linked
# here: https://cloud.google.com/run/docs/configuring/services/secrets
