on:
  push:
    branches:
      - main
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    env:
      # For non-secret environment variables, there's no need to use GitHub's
      # repository variables. These are just here for demonstration purposes.
      PUBLIC_ENV_VAR_ONE: ${{ vars.ENV_VAR_ONE }}
      PUBLIC_ENV_VAR_TWO: ${{ vars.ENV_VAR_TWO }}
      # For secret environment variables, use GitHub's repository secrets.
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Set up Playwright
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run test
      - name: Build app
        run: npm run build
      - name: Copy necessary files to build directory
        run: cp package*.json Dockerfile build
      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Install GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
      - name: Build and deploy to Cloud Run
        run: gcloud run deploy app --source build --platform managed --memory 128Mi --region ${{ vars.GCP_SERVICE_REGION }} --allow-unauthenticated --project ${{ vars.GCP_PROJECT_ID }}
